apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-tools
  labels:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    helm.sh/chart: {{ include "temporal.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: admin-tools
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "temporal.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: admin-tools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "temporal.name" . }}
        helm.sh/chart: {{ include "temporal.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
        app.kubernetes.io/component: admin-tools
        app.kubernetes.io/part-of: {{ .Chart.Name }}
    spec:
      containers:
        - name: admin-tools
          image: temporalio/admin-tools:1.20
          imagePullPolicy: IfNotPresent
          env:
            - name: SQL_HOST
              value: temporaldb.temporalio.svc.cluster.local
            - name: SQL_USER
              value: temporal
            - name: SQL_PASSWORD
              value: temporal
            - name: SQL_PORT
              value: "5432"
            - name: SQL_PLUGIN
              value: postgres12
            - name: TEMPORAL_CLI_ADDRESS
              value: frontend.temporalio.svc.cluster.local:7233
